### ISSUE TITLE
Specify supported python versions

### ISSUE THREAD

**Issue by glass1720** [conglu1997/SynthER#2]
Hey!

Many thanks for your interesting paper and providing your code. 

I have some installation trouble and had to try a few different python versions to get the requirements to install successfully. Specifically, I found for more recent python versions pip was unable to build the wheel for dm-control.  It could be helpful to specify in the readme which versions you have used to simplify this process. I found 3.7.9 worked. 

Thanks,

Glass

**Comment by conglu1997** [comment]
Thanks for the feedback, will note this down. We used Python 3.8.
